_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    glob:
      - '*.html'
    name: Pages
    icon: data_usage
    url: /[full_slug]
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Asia/Riyadh
_inputs:
  content:
    type: html
    options:
      bold: true
      italics: true
      underline: true
  layout:
    type: select
    label: Layout
    comment: Choose the page layout type
    options:
      values: 
        - default
    cascade: true
  # This header style section is a perfect example for making the dropdown for the client in cloud cannon
  screen-height:
    type: select
    label: Screen height
    comment: Choose the height of the banner
    options:
      values: 
        - full 
        - 80%
        - 60%
    cascade: true
  image-horizontal-focal-point:
    type: select
    label: Horizontal image focal point
    comment: Choose where the focus/positioning of the image should be
    options:
      values: 
        - center
        - left
        - right
    cascade: true
  image-vertical-focal-point:
    type: select
    label: Vertical image focal point
    comment: Choose where the focus/positioning of the image should be
    options:
      values: 
        - center
        - top
        - bottom
    cascade: true
  image-placement:
    type: select
    label: Image placement
    comment: Choose whether the image is on the left or right
    options:
      values: 
        - left
        - right
    cascade: true
  text-placement:
    type: select
    label: Text placement
    comment: Choose where the text in placed in relation to the image
    options:
      values: 
        - top
        - center
        - bottom
    cascade: true
  large-text-width:
    type: select
    label: Large text width
    comment: Choose whether the large text takes up half or the full width of the page
    options:
      values: 
        - half
        - full
    cascade: true
  paragraph-text-width:
    type: select
    label: Paragraph text width
    comment: Choose whether the paragraph text takes up half or the full width of the page
    options:
      values: 
        - half
        - full
    cascade: true
  large-text-placement:
    type: select
    label: Large text placement
    comment: Choose whether the large text is on the left or right. If text will be full width, choose left here.
    options:
      values: 
        - right
        - left
    cascade: true
  text-alignment:
    type: select
    label: Text alignment
    comment: Choose whether the text is aligned to the left or right
    options:
      values: 
        - left
        - center
        - right
    cascade: true
  large-text-alignment:
    type: select
    label: Large text alignment
    comment: Choose whether the large text is aligned to the left or right
    options:
      values: 
        - left
        - center
        - right
    cascade: true
  paragraph-text-alignment:
    type: select
    label: Paragraph text alignment
    comment: Choose whether the paragraph text is aligned to the left or right
    options:
      values: 
        - left
        - center
        - right
    cascade: true
  overlay:
    type: select
    label: Image overlay color
    comment: Choose what opaque color should go over the image to make the text stand out. Note that for dark, only use the 'dark navy' or 'angel blue' color schemes down below.
    options:
      values: 
        - overlay-light
        - overlay-dark
    cascade: true
  scheme-name:
    type: select
    label: Color scheme for the block
    comment: Choose which background color to use, then the text, button and highlight colors will be chosen automatically
    options:
      values: 
        - white-background-green-highlight
        - white-background-blue-highlight
        - angel-blue-background
        - dark-navy-background
        - medium-blue-background
        - light-blue-background
        - v-light-blue-background
        - green-background
        - light-green-background
    cascade: true
  type:
    type: select
    label: Information type
    comment: Choose what information is pulled into this block
    options:
      values: 
        - calendar
        - donate
        - employment
        - financials
        - news
        - people
        - programs
        - testimonials
        - volunteer opportunities
    cascade: true
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: true
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes_elements:
      inline: none
      block: space right
      ul: below
      ol: below
      blockquote: below
      p: below
      img: below
      hr: below
      table: below
      li: none
