_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    glob:
      - '*.html'
    name: Pages
    icon: data_usage
    url: /[full_slug]
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  content:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  layout:
    type: select
    options:
      allow_empty: true
      values:
        - default
    label: Layout
    comment: Choose the page layout type
    cascade: true
  screen-height:
    type: select
    options:
      allow_empty: true
      values:
        - full
        - 80%
        - 60%
    label: Screen height
    comment: Choose the height of the banner
    cascade: true
  image-horizontal-focal-point:
    type: select
    options:
      allow_empty: true
      values:
        - center
        - left
        - right
    label: Horizontal image focal point
    comment: Choose where the focus/positioning of the image should be
    cascade: true
  image-vertical-focal-point:
    type: select
    options:
      allow_empty: true
      values:
        - center
        - top
        - bottom
    label: Vertical image focal point
    comment: Choose where the focus/positioning of the image should be
    cascade: true
  image-placement:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - right
    label: Image placement
    comment: Choose whether the image is on the left or right
    cascade: true
  text-placement:
    type: select
    options:
      allow_empty: true
      values:
        - top
        - center
        - bottom
    label: Text placement
    comment: Choose where the text in placed in relation to the image
    cascade: true
  large-text-width:
    type: select
    options:
      allow_empty: true
      values:
        - half
        - full
    label: Large text width
    comment: Choose whether the large text takes up half or the full width of the page
    cascade: true
  paragraph-text-width:
    type: select
    options:
      allow_empty: true
      values:
        - half
        - full
    label: Paragraph text width
    comment: >-
      Choose whether the paragraph text takes up half or the full width of the
      page
    cascade: true
  large-text-placement:
    type: select
    options:
      allow_empty: true
      values:
        - right
        - left
    label: Large text placement
    comment: >-
      Choose whether the large text is on the left or right. If text will be
      full width, choose left here.
    cascade: true
  text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Text alignment
    comment: Choose whether the text is aligned to the left or right
    cascade: true
  large-text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Large text alignment
    comment: Choose whether the large text is aligned to the left or right
    cascade: true
  paragraph-text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Paragraph text alignment
    comment: Choose whether the paragraph text is aligned to the left or right
    cascade: true
  overlay:
    type: select
    options:
      allow_empty: true
      values:
        - overlay-light
        - overlay-dark
    label: Image overlay color
    comment: >-
      Choose what opaque color should go over the image to make the text stand
      out. Note that for dark, only use the 'dark navy' or 'angel blue' color
      schemes down below.
    cascade: true
  scheme-name:
    type: select
    options:
      allow_empty: true
      values:
        - white-background-green-highlight
        - white-background-blue-highlight
        - angel-blue-background
        - dark-navy-background
        - medium-blue-background
        - light-blue-background
        - v-light-blue-background
        - green-background
        - light-green-background
    label: Color scheme for the block
    comment: >-
      Choose which background color to use, then the text, button and highlight
      colors will be chosen automatically
    cascade: true
  type:
    type: select
    options:
      allow_empty: true
      values:
        - calendar
        - donate
        - employment
        - financials
        - news
        - people
        - programs
        - testimonials
        - volunteer opportunities
    label: Information type
    comment: Choose what information is pulled into this block
    cascade: true
_structures:
  blocks:
    style: select
    id_key:
    values:
timezone: Asia/Riyadh
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: true
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes_elements:
      inline: none
      block: space right
      ul: below
      ol: below
      blockquote: below
      p: below
      img: below
      hr: below
      table: below
      li: none
