_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    glob:
      - '*.html'
    name: Pages
    icon: data_usage
    url: /[full_slug]
    disable_url: false
    description: ''
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: _data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  id:
    type: text
    hidden: true
    cascade: true
  content:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  phone-number:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  number:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  featured:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  date:
    type: html
    options:
      bold: true
      italics: true
      underline: true
    cascade: true
  layout:
    type: select
    options: 
      allow_empty: true
      values: 
        - default
    label: Layout
    comment: Choose the page layout type
    cascade: true
  screen-height:
    type: select
    options:
      allow_empty: false
      values:
        - full
        - 80%
        - 60%
    label: Screen height
    comment: Choose the height of the banner
    cascade: true
  image-horizontal-focal-point:
    type: select
    options:
      allow_empty: true
      values:
        - center
        - left
        - right
    label: Horizontal image focal point
    comment: Choose where the focus/positioning of the image should be
    cascade: true
  image-vertical-focal-point:
    type: select
    options:
      allow_empty: true
      values:
        - center
        - top
        - bottom
    label: Vertical image focal point
    comment: Choose where the focus/positioning of the image should be
    cascade: true
  image-placement:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - right
    label: Image placement
    comment: Choose whether the image is on the left or right
    cascade: true
  text-placement:
    type: select
    options:
      allow_empty: true
      values:
        - top
        - center
        - bottom
    label: Text placement
    comment: Choose where the text in placed in relation to the image
    cascade: true
  large-text-width:
    type: select
    options:
      allow_empty: false
      values:
        - half
        - full
    label: Large text width
    comment: Choose whether the large text takes up half or the full width of the page
    cascade: true
  width:
    type: select
    options:
      allow_empty: false
      values:
        - half
        - full
        - third
    label: Text/box width
    comment: >-
      Choose whether the input takes up one-third, half or the full width of the page
    cascade: true
  name:
    type: text
    label: Name for receiving the form information
    options: 
      allow_empty: false
    comment: When you receive the form in your email, this is what the form will export to you
  label:
    type: text
    label: Title above the input area
    options: 
      allow_empty: false
    comment: If you want to label the form input, this is where you add the title
  paragraph-width:
    type: select
    options:
      allow_empty: false
      values:
        - half
        - full
    label: Paragraph text width
    comment: >-
      Choose whether the paragraph text takes up half or the full width of the page
    cascade: true
  large-text-placement:
    type: select
    options:
      allow_empty: false
      values:
        - right
        - left
    label: Large text placement
    comment: >-
      Choose whether the large text is on the left or right. If text will be full width, choose left here.
    cascade: true
  text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Text alignment
    comment: Choose whether the text is aligned to the left, center, or right
    cascade: true
  large-text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Large text alignment
    comment: Choose whether the large text is aligned to the left, center, or right
    cascade: true
  paragraph-text-alignment:
    type: select
    options:
      allow_empty: true
      values:
        - left
        - center
        - right
    label: Paragraph text alignment
    comment: Choose whether the paragraph text is aligned to the left, center, or right
    cascade: true
  hide-top-padding:
    type: checkbox
    label: Stacked block top padding
    comment: Check this box if the block above is the same block and background color. This will remove some of the top padding so it doesn't feel like there's an awkward space.
    cascade: true
  hide-bottom-padding:
    type: checkbox
    label: Stacked block bottom padding
    comment: Check this box if the block below is the same block and background color. This will remove some of the bottom padding so it doesn't feel like there's an awkward space.
    cascade: true
  heading-has-long-words:
    type: checkbox
    label: This heading has a long word
    comment: Check this box if the heading has a long word in it that messes with things - this will allow you to keep the hierarchy while making the text just slighly smaller
    cascade: true
  card-description:
    type: checkbox
    label: Card description
    comment: Do you want these cards to show the short description?
    cascade: true
  color:
    type: select
    options:
      allow_empty: false
      values:
        - var(--featured-color-dark-navy)
        - var(--featured-color-angel-blue)
        - var(--featured-color-medium-blue)
    label: Card background color
    comment: >-
      Choose what color you want the background of the card to be.
    cascade: true
  overlay:
    type: select
    options:
      allow_empty: false
      values:
        - overlay-light
        - overlay-dark
    label: Image overlay color
    comment: >-
      Choose what opaque color should go over the image to make the text stand
      out. Note that for dark, only use the 'dark navy' or 'angel blue' color
      schemes down below.
    cascade: true
  scheme-name:
    type: select
    options:
      allow_empty: true
      values:
        - white-background-green-highlight
        - white-background-blue-highlight
        - angel-blue-background
        - dark-navy-background
        - medium-blue-background
        - light-blue-background
        - v-light-blue-background
        - green-background
        - light-green-background
    label: Color scheme for the block
    comment: >-
      Choose which background color to use, then the text, button and highlight
      colors will be chosen automatically
    cascade: true
  type:
    type: select
    options:
      allow_empty: true
      values:
        - calendar
        - donate
        - employment
        - financials
        - news
        - people
        - programs
        - testimonials
        - volunteer opportunities
    label: Information type
    comment: Choose what information is pulled into this block
    cascade: true
  form-type:
    type: select
    options:
      allow_empty: false
      values:
        - text
        - email
        - phone
        - textarea
    label: Form input type
    comment: Choose what type of information people are putting into the form (text is for things like forst and last name, textarea is for a larger area for text)
    cascade: true
_structures:
  blocks:
    style: select
    values:
      - label: full image header
        value:
          id: full-image-header
          heading_html:
          image:
          image-horizontal-focal-point:
          image-vertical-focal-point:
          overlay:
          scheme-name:
      - label: half image header
        value:
          id: half-image-header
          image:
          alt:
          heading_html:
          heading-has-long-words:
          text_html:
          button-1-text: 
          button-1-link: 
          button-2-text: 
          button-2-link: 
          screen-height: 
          image-placement: 
          image-horizontal-focal-point: 
          image-vertical-focal-point: 
          text-placement:
          scheme-name:
      - label: image text numbers
        value:
          id: image-text-numbers
          image:
          alt:
          caption:
          section-heading_html:
          text-block-heading_html:
          heading-has-long-words:
          facts-loop:
            - featured:
              text:
          description_html:
          button-1-text: 
          button-1-link: 
          button-2-text: 
          button-2-link: 
          image-placement: 
          image-horizontal-focal-point: 
          image-vertical-focal-point: 
          text-placement:
          large-text-alignment:
          scheme-name:
      - label: text banner
        value:
          id: text-banner
          heading_html:
          text_html:
          large-text-width: 
          paragraph-width: 
          large-text-placement: 
          large-text-alignment: 
          paragraph-text-alignment: 
          button-1-text: 
          button-1-link: 
          button-2-text: 
          button-2-link: 
          scheme-name:
      - label: info cards
        value:
          id: info-cards
          section-heading:
          type:
          card-description:
          text-alignment:
          scheme-name:
      - label: info block
        value:
          id: info-block
          section-heading:
          large-text-alignment:
          type:
          scheme-name:
      - label: facts
        value:
          id: facts
          section-heading:
          facts-loop:
            - featured:
              text:
          text-alignment:
          scheme-name:
      - label: interactive cards
        value:
          id: interactive-cards
          section-heading:
          card-loop:
            - front:
              back:
          text-alignment:
          scheme-name:
      - label: form
        value:
          id: form
          section-heading:
          large-text-alignment:
          section-text:
          inputs:
          - form-type: text
            name: First name
            label: First name
            placeholder-text: John
            width: half
            required: true
          - form-type: textarea
            name: Message
            label: Message
            placeholder-text: Write your message here
            width: full
            required: true
          scheme-name:
      - label: accordion
        value:
          id: accordion
          section-heading:
          large-text-alignment:
          text-alignment: 
          accordion-loop:
            - question:
              answer_html:
          scheme-name:
      - label: calendar at a glance
        value:
          id: calendar-at-a-glance
          section-heading:
          large-text-alignment:
          type:
          text-alignment:
          scheme-name:
      - label: testimonials
        value:
          id: testimonials
          section-heading:
          large-text-alignment:
          type:
          show:
          text-alignment:
          scheme-name:
      - label: button banner
        value:
          id: button-banner
          button-loop:
            - text:
              link:
          scheme-name:
      - label: image grid
        value:
          id: image-grid
          hide-top-padding: 
          hide-bottom-padding: 
          image-loop:
            - image:
              alt:
          scheme-name:
      - label: logo image grid
        value:
          id: logo-image-grid
          image-loop:
            - image:
              alt:
              link:
          scheme-name:
      - label: infographic image
        value:
          id: infographic-image
          image:
          image-mob:
          alt:
      - label: map
        value:
          id: map
          section-heading:
          large-text-alignment: 
          address:
          scheme-name: 
      - label: financial cards
        value:
          id: financial-cards
          section-heading:
          type:
          scheme-name:
timezone: Asia/Riyadh
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: true
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes_elements:
      inline: none
      block: space right
      ul: below
      ol: below
      blockquote: below
      p: below
      img: below
      hr: below
      table: below
      li: none
