[[redirects]]
  from = "/events/T4YC-2025"
  to = "https://raceroster.com/events/2025/103994/tri-4-your-cure-2025"

[[redirects]]
  from = "/resources"
  to = "/angel-packs"

[[redirects]]
  from = "/shop"
  to = "https://angelpacks.mnangel.org/"